name: Build and Deploy to EC2

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      run: |
        IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/spring-react-app:latest
        docker build -t $IMAGE .
        docker push $IMAGE

    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/spring-react-app:latest
          docker stop app || true
          docker rm app || true
          docker run -d --name app -p 80:8080 ${{ secrets.DOCKERHUB_USERNAME }}/spring-react-app:latest

          
